provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  jsonrouter:
    lang: go
    handler: ./jsonrouter
    image: jsonrouter:latest
    environment:
      config: "{ routes: []}"
  labeling:
    lang: golang-http
    handler: ./labeling
    image: labeling:latest
